### PR TITLE
I've no idea why this is not working

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by agramfort** [comment]
what is not working?

**Comment by massich** [comment]
well, everything is broken! 

travis gives you [this](https://travis-ci.org/massich/mne-python/jobs/430548849#L2685) error:

```sh
    raw._first_time, raw._last_time))
E   TypeError: must be real number, not NoneType
```

which doesn't make much of a sense since this is what we are doing 

```diff
        logger.info('    Range : %d ... %d =  %9.3f ... %9.3f secs' % (
                     self.first_samp, self.last_samp,
-                    float(self.first_samp) / info['sfreq'],
-                    float(self.last_samp) / info['sfreq']))
+                    self._first_time, self._last_time))
```
and `_first_time` is: 
https://github.com/massich/mne-python/blob/d0a1155f06ebe9c5d2c6217de5d1ab0abd06b992/mne/io/base.py#L641

If it complains now for `None` it should complain before.

**Comment by massich** [comment]
it has to do with the fact that `raw` is not `BaseRaw` but `_RawShell`

**Comment by massich** [comment]
-1 on merging this, its not worth it.

**Comment by massich** [comment]
or maybe is broken. 'cos raw is not actually a BaseRaw but _RawShell

https://github.com/massich/mne-python/blob/12644b41d637ee5f569471213dd2a38aa64edfab/mne/io/fiff/raw.py#L201-L203

**Comment by agramfort** [comment]
if it's not worth it just move on

**Pull request closed without merging**
